<a href="https://colab.research.google.com/github/Eduardostca/ML_/blob/main/Graded_Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DAB200 -- Graded Lab 2

In this lab, you will gain some experience in converting non-numeric features in a dataset to numeric so they can be used in a machine learning model.

**Target**: to predict `Comb Unadj FE - Conventional Fuel`

**Note**: There may be other "features" similar to the target, so these need to be removed from the data.

**Data set**: make sure you use the data assigned to your group!

| Groups | Data set |
| :-: | :-: |
| 1-4 | veh15.csv |
| 5-7 | veh16.csv |
| 8-10 | veh17.csv |
| 11-14 | veh18.csv |
| 15-18 | veh19.csv |

**Important Notes:**
- Use [Chapter 6](https://mlbook.explained.ai/catvars.html) of the textbook as a **guide**:
     - you only need to use **random forest** models;
- Code submitted for this lab should be:
     - error free
         - to make sure this is the case, before submitting, close all Jupyter notebooks, exit Anaconda, reload the lab notebook and execute all cells
     - final code
         - this means that I don't want to see every piece of code you try as you work through this lab but only the final code; only the code that fulfills the objective
- Use the **out-of-bag score** to evaluate models
     - Read Section 5.2 carefully so that you use this method properly
     - The oob score that you provide should be the average of 10 runs
- Don't make assumptions!

### Part 0

Please provide the following information:
 - Group Number 14
 - Group Members

Noushin Asadsamani (0829532)

Eduardo Chavez Barrientos (0828349)

Prasanna Kumar Loganathan (0827541)

### Part 1 - Create and evaluate an initial model

In this part you should:
 - read in the data
 - isolate all numeric features from original data set
 - verify there are no missing values
 - create and evaluate a baseline model

#### Code (15 marks)

In [2]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import *
from sklearn.model_selection import train_test_split

### -- Reading the data:

In [6]:
df = pd.read_csv('https://github.com/Eduardostca/ML_/blob/main/veh18.csv?raw=true')
df

,Eng Displ,# Cyl,Comb Unadj FE - Conventional Fuel,# Gears,Max Ethanol % - Gasoline,Intake Valves Per Cyl,Exhaust Valves Per Cyl,Fuel Metering Sys Desc,Air Aspiration Method Desc,Trans Desc,Cyl Deact?,Var Valve Lift?
0,5.2,12,22.8444,8,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Semi-Automatic,Y,N
1,4.0,8,26.6603,8,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Semi-Automatic,N,N
2,6.0,12,20.4316,8,10.0,2,2,Multipoint/sequential fuel injection,Naturally Aspirated,Semi-Automatic,N,N
3,6.0,12,21.3382,8,10.0,2,2,Multipoint/sequential fuel injection,Naturally Aspirated,Semi-Automatic,N,N
4,1.5,3,36.7632,6,10.0,2,2,Spark Ignition Direct Injection,Turbocharged,Semi-Automatic,N,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
1158,2.0,4,34.2176,8,10.0,2,2,Spark Ignition Direct Injection,Turbocharged,Semi-Automatic,N,N
1159,3.8,8,23.7711,7,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1160,3.8,8,23.7711,7,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1161,3.8,8,23.7711,7,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1162,4.0,8,22.6765,7,10.0,2,2,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1163 entries, 0 to 1162
Data columns (total 12 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Eng Displ                          1163 non-null   float64
 1   # Cyl                              1163 non-null   int64
 2   Comb Unadj FE - Conventional Fuel  1163 non-null   float64
 3   # Gears                            1163 non-null   int64
 4   Max Ethanol % - Gasoline           1163 non-null   float64
 5   Intake Valves Per Cyl              1163 non-null   int64
 6   Exhaust Valves Per Cyl             1163 non-null   int64
 7   Fuel Metering Sys Desc             1163 non-null   object
 8   Air Aspiration Method Desc         1163 non-null   object
 9   Trans Desc                         1163 non-null   object
 10  Cyl Deact?                         1163 non-null   object
 11  Var Valve Lift?                    1163 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 109.2+ KB

### -- Isolating all numeric features:

In [9]:
df_num = df.select_dtypes(include = 'number')
df_num

,Eng Displ,# Cyl,Comb Unadj FE - Conventional Fuel,# Gears,Max Ethanol % - Gasoline,Intake Valves Per Cyl,Exhaust Valves Per Cyl
0,5.2,12,22.8444,8,10.0,2,2
1,4.0,8,26.6603,8,10.0,2,2
2,6.0,12,20.4316,8,10.0,2,2
3,6.0,12,21.3382,8,10.0,2,2
4,1.5,3,36.7632,6,10.0,2,2
...,...,...,...,...,...,...,...
1158,2.0,4,34.2176,8,10.0,2,2
1159,3.8,8,23.7711,7,10.0,2,2
1160,3.8,8,23.7711,7,10.0,2,2
1161,3.8,8,23.7711,7,10.0,2,2
1162,4.0,8,22.6765,7,10.0,2,2

### -- Verifying missing values:

In [10]:
df.isna().sum()

Eng Displ                            0
# Cyl                                0
Comb Unadj FE - Conventional Fuel    0
# Gears                              0
Max Ethanol % - Gasoline             0
Intake Valves Per Cyl                0
Exhaust Valves Per Cyl               0
Fuel Metering Sys Desc               0
Air Aspiration Method Desc           0
Trans Desc                           0
Cyl Deact?                           0
Var Valve Lift?                      0
dtype: int64

### -- Creating a baseline model:

In [11]:
X = df_num.drop(['Comb Unadj FE - Conventional Fuel'], axis=1)
y = df_num['Comb Unadj FE - Conventional Fuel']

In [17]:
oob_scores = []
predictions_1 =[]
for i in range(10):
    model_1 = RandomForestRegressor(n_estimators=100, n_jobs=-1, oob_score=True)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    model_1.fit(X_train, y_train)
    oob_scores.append(model_1.oob_score_)

avg_oob_scores_1 = sum(oob_scores) / len(oob_scores)
print(f"Average OOB score over 10 runs for model 1: {avg_oob_scores_1:.4f}")

Average OOB score over 10 runs for model 1: 0.6934

### Question (5 marks)
#### Explain the purpose of creating a baseline model.

A baseline model works as a reference point to compare the performance of more complex models and have a better understanding if the model improvements are effective or not. It also helps to ensure that the data is properly prepared for the model and the implementation is correct. It helps to identify any major issues or anomalies in the data. If the baseline model performance is poor, further fixes are needed to improve it.

### Part 2 - Convert non-numeric features to numeric

In this part you should:
 - convert **all** non-numeric features to numeric
 - one of the conversions should use **one-hot encoding**
 - create **one new feature** by combining 2 or more of the existing features

#### Code (25 marks)

## -- Converting all non-numeric features:

In [18]:
# Storing NOT numeric features:
df_no_num = df[['Fuel Metering Sys Desc', 'Air Aspiration Method Desc', 'Trans Desc', 'Cyl Deact?', 'Var Valve Lift?']]
df_no_num

,Fuel Metering Sys Desc,Air Aspiration Method Desc,Trans Desc,Cyl Deact?,Var Valve Lift?
0,Multipoint/sequential fuel injection,Turbocharged,Semi-Automatic,Y,N
1,Multipoint/sequential fuel injection,Turbocharged,Semi-Automatic,N,N
2,Multipoint/sequential fuel injection,Naturally Aspirated,Semi-Automatic,N,N
3,Multipoint/sequential fuel injection,Naturally Aspirated,Semi-Automatic,N,N
4,Spark Ignition Direct Injection,Turbocharged,Semi-Automatic,N,Y
...,...,...,...,...,...
1158,Spark Ignition Direct Injection,Turbocharged,Semi-Automatic,N,N
1159,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1160,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1161,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N
1162,Multipoint/sequential fuel injection,Turbocharged,Automatic,N,N

In [26]:
# Making sure that there are not NaN as strings:
columns = ['Fuel Metering Sys Desc', 'Air Aspiration Method Desc', 'Trans Desc', 'Cyl Deact?', 'Var Valve Lift?']
for column in columns:
    print(df_no_num[[column]].value_counts(), "\n")

Fuel Metering Sys Desc
Spark Ignition Direct Injection             834
Multipoint/sequential fuel injection        251
Spark Ignition direct & ported injection     78
dtype: int64

Air Aspiration Method Desc
Turbocharged                  614
Naturally Aspirated           489
Supercharged                   51
Turbocharged+Supercharged       9
dtype: int64

Trans Desc
Semi-Automatic                                                       529
Automatic                                                            246
Manual                                                               165
Automated Manual- Selectable (e.g. Automated Manual with paddles)    103
Selectable Continuously Variable (e.g. CVT with paddles)              46
Automated Manual                                                      45
Continuously Variable                                                 29
dtype: int64

Cyl Deact?
N             1017
Y              146
dtype: int64

Var Valve Lift?
N                  806
Y                  357
dtype: int64

#### Explanation (25 marks)

Please provide an explanation for each conversion from non-numeric to numeric and state why this conversion is appropriate. Please also provide an explanation of the new feature created.

### Part 3 - Create and evaluate a final model

In this part you should:
 - create and evaluate a model using all the features from Parts 1 and 2 above

#### Code (15 marks)

### Part 4 - Feature importances and comparison (10 marks)

In this part you should:
 - calculate the percent difference between the results of Part 1 and Part 3 (make sure you are using the correct formula for percent difference)
 - based on the percent difference, state whether or not the results of Part 3 are an improvement over the results of Part 1
 - use the `rfpimp` package to calculate and display the feature importances for all features

#### Question (5 marks)

Based on the feature importances, are any features that you think should be removed from the data set.  Why do you think these features should be removed?